# Site settings
title: 3DRecon Dataset
email: 
# description: "Musings of a Computer Scientist."
baseurl: "/3drecon_dataset"
url: "https://imkaywu.github.io"
# twitter_username: karpathy
github_username:  imkaywu

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
